### ISSUE TITLE
歌单(我喜欢的音乐)无法获取内容,其他的歌单都可以正常获取

### ISSUE THREAD

**Issue by logique233** [KusStar/rewind-apks#10]
![3150931](https://user-images.githubusercontent.com/34376539/99039486-626b1480-25c2-11eb-87e8-9772fdf5dd15.png)
![13150950](https://user-images.githubusercontent.com/34376539/99039497-65fe9b80-25c2-11eb-969e-69141dbe8692.png)

已登陆网易云
手机系统miui12

**Comment by KusStar** [comment]
这确实需要更改，等下个版本吧
