### ISSUE TITLE
播放出错

### ISSUE THREAD

**Issue by duskdusts** [KusStar/rewind-apks#17]
![Screenshot_2021-02-14-16-26-52-342_com kuss rewind](https://user-images.githubusercontent.com/60814886/107871998-c4992580-6ee1-11eb-8d04-6c141e52fcbd.jpg)
播放出错
倒带版本：3.2.0
手机型号：红米k30pro
miui版本：12.0.9稳定版
安卓版本： 10
网络环境：wifi和中国移动数据下均尝试
复现概率：100%
其他：尝试过清数据，无用

**Comment by KusStar** [comment]
修复中

**Comment by duskdusts** [comment]
readme页面下载的倒带还是报错，刚加了电报群组，上面的3.2.0不报错
