### ISSUE TITLE
3.2播放闪退

### ISSUE THREAD

**Issue by Athethethe** [KusStar/rewind-apks#18]
![Screenshot_2021-02-14-23-54-59-476_com kuss rewind](https://user-images.githubusercontent.com/58813300/107881756-a6064f00-6f20-11eb-811f-b84a4e902d10.jpg)
![Screenshot_2021-02-14-23-55-18-694_com kuss rewind](https://user-images.githubusercontent.com/58813300/107881758-a868a900-6f20-11eb-8cd3-7350f5be9c25.jpg)

MIUI12，启动正常，播放闪退。
64和32的包都试了😂

**Comment by KusStar** [comment]
https://github.com/KusStar/rewind-apks/blob/master/app-arm64-v8a-release.apk
直接用 Github 的下载吧，链接里的 CDN 缓存了
