### ISSUE TITLE
BUG汇报

### ISSUE THREAD

**Issue by logique233** [KusStar/rewind-apks#19]
1. 3.16版本线控切歌可以正常运行,但是最新版线控切歌不起作用.
2. 最新版的应用崩溃的很平凡,从桌面启动应用偶尔就会崩溃2~3次,才能正常启动.
3. 自动切换下一首歌时偶尔一直卡在缓冲上了,可能是网路的问题,但是3.16版本没有遇到这个问题.

手机系统MIUI 12.0.7

**Comment by KusStar** [comment]
1. 下个版本修复。
2. 有崩溃日志吗？
3. 什么曲目？

**Comment by logique233** [comment]
2.启动应用直接闪退,没看到崩溃日志
3. 不是特定的某首歌,
   自动切换下一首歌曲并缓冲音乐时,偶尔会卡在缓冲这一步上,一直等待.
   (出现这种情况时只要切换一下,播放就正常了)
   大概率是我手机网络的问题
