### ISSUE TITLE
希望添加听歌识曲功能

### ISSUE THREAD

**Issue by fykwgl** [KusStar/rewind-apks#2]
很不错的软件，用了一段时间后果断卸载网抑云，可惜少了听歌识曲功能，不知这个功能是否有接口？总之非常感谢作者开发了这款纯粹的听音乐软件，如果能有听歌识曲功能的话就能彻底抛弃官方app了。

**Comment by KusStar** [comment]
听歌识曲搞不到接口，实现不了。
可以用识曲软件代替，如「Q音探歌」、「Shazam lite」。
