### ISSUE TITLE
希望能添加背景图片高斯模糊调节功能

### ISSUE THREAD

**Issue by fykwgl** [KusStar/rewind-apks#6]
现有的是一个开关，打开以后感觉背景图模糊的程度很重，不知能否把这个开关变成模糊程度可调的滑杆，添加模糊调节功能？

**Comment by KusStar** [comment]
加个滑杆也行。
现在的模糊是动态添加的，其实蛮浪费资源的。
更建议自行加工图片后再将其设为背景。
