### ISSUE TITLE
歌单只能读取1000首

### ISSUE THREAD

**Issue by holder-fo** [KusStar/rewind-apks#7]
我知道网易云播放列表只能1000首，但是歌单里面可以显示超过1000首全部歌曲，在倒带里面歌单就只能显示1000首（如默认的我喜欢的音乐），超过的部分歌曲歌单内部搜索也搜索不到（网易云歌单里面搜索没问题）。不知道是我这边的问题还是应用就是不支持？

**Comment by KusStar** [comment]
不支持

**Comment by holder-fo** [comment]
大佬不考虑支持么？很多歌单都超过1000首，歌单里面搜索1000首以外的歌能支持么？
