### ISSUE TITLE
希望添加“不感兴趣”选项

### ISSUE THREAD

**Issue by fykwgl** [KusStar/rewind-apks#8]
以前用网页登网抑云账号听每日推荐时遇到不喜欢的歌曲，都会直接点“不感兴趣”来滤掉；现在用倒带发现每日推荐里的歌没有这一选项（右侧三点里只有评论、分享、歌词、克隆），只能到网页版上去点掉，不知能否在后续版本里加上这一项？

**Comment by KusStar** [comment]
行
